name : Hello World!

on: 
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Display Current Date
        run: date
      - name: List Directory Contents
        run: ls -alh