name : Lint Workflow

on: 
  push:
    branches:
      - main

jobs:
  lint_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check Directory contents
        run: ls
      - name: Move to the project directory
        run: cd ./full-stack-open-pokedex
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run eslint